server:
  servlet:
    context-path: /sqlite-service
spring:
  datasource:
#    url: jdbc:sqlite:data.db
#    url: jdbc:sqlite:identifier.sqlite
    url: jdbc:sqlite::resource:db/identifier.sqlite
    driver-class-name:  org.sqlite.JDBC
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLiteDialect
